### ISSUE TITLE
'module' object is not callable

### ISSUE THREAD

**Issue by sunzxcml** [Pierre-Sassoulas/pySankey#10]
when I use your data to do a simple test, 
but when I type

ax = sankey(
      left=df['customer'].values[1:], right=df['good'].values[1:],
      rightWeight=weight, leftWeight=weight, aspect=20
)

it shows "'module' object is not callable"

Ii tried "pySankey2" and "pySankeyBeta" none of them works. when install one, I will unistall the other
when I use help(sankey) all the parameters are allowed

I want to know the reason

Look forward to your reply
Thank you very much

**Comment by Pierre-Sassoulas** [comment]
The only thing that is called here is `sankey` so it means that `sankey` is a module and not the function that you need. You should probably change the importe to `from sankey import sankey`.
