### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by nedwards-loop** [Pierre-Sassoulas/pySankey#24]
`ModuleNotFoundError Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_29264/4168780170.py in
1 import pandas as pd
----> 2 from pysankey import Sankey

ModuleNotFoundError: No module named 'pysankey'`

Output of pip freeze:

pySankeyBeta==1.4.0

**Comment by Pierre-Sassoulas** [comment]
This should work, the pip freeze must be in another env than the one you're using.
