### ISSUE TITLE
ModuleNotFoundError: No module named 'pysankey'

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [Pierre-Sassoulas/pySankey#8]
> Hello Pierre.
> I've installed PySankey, but when I try to import it into Anaconda, I'm getting "no module found".
>   For "from pysankey import sankey" - I get `ModuleNotFoundError: No module named 'pysankey'`
>   For "import sankey" - I get `ModuleNotFoundError: No module named 'pysankey'"`
> When I do "pip install pySankeyBeta==1.1.0" I get "Requirement already satisfied".
> When I did "pip freeze", I got:
> ```pySankey==0.0.1 pySankeyBeta==1.1.0```
> What could possibly be going on?
> Thanks.

**Comment by Pierre-Sassoulas** [comment]
Hello,

Can you try to remove pySankey with "pip uninstall pySankey" ? I think the two packages might be conflicting with each other.

Then you should be able to import sankey without the ModuleNotFoundError.

Regards,

**Comment by Jaguar100** [comment]
I "successfully uninstalled pySankey-0.0.1". Then after trying "from PySankey import Sankey", I got: "ModuleNotFoundError: No module named 'pysankey'

This is the same error message I was originally getting.

**Comment by Pierre-Sassoulas** [comment]
I think the capitalization in `from PySankey import Sankey` is wrong, you should use `from pysankey import sankey`.

```
>>> from PySankey import Sankey
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PySankey'
>>> from pysankey import sankey
>>> sankey
<function sankey at 0x7f53cf43a400>
```

**Comment by Jaguar100** [comment]
Same Error message with lowercase:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-59-19eb456f14ed> in <module>
----> 1 from pysankey import sankey

ModuleNotFoundError: No module named 'pysankey'

**Comment by Pierre-Sassoulas** [comment]
This error message indicates that `pySankeyBeta` is not properly installed in the environment where you try to import it. I think you're not trying to import in the same environment than the one where you installed `pySankeyBeta`. If you're under a Unix system, you can use the step used in my message above in order to have a workable solution in a virtualenv.

**Comment by Jaguar100** [comment]
I'm not a Unix user. This is Windows. Its the same pip / conda install I do for all libraries. I've never delineated a different location for any install.

**Comment by Pierre-Sassoulas** [comment]
Can you try to import with: `from pySankey import sankey`, see here : https://github.com/Pierre-Sassoulas/django-survey/issues/58

There seems to be something OS dependant here.

**Comment by Jaguar100** [comment]
Thanks Pierre. That seems to have worked. Of course I had to first install pySankey - as opposed to PySankey or pysankey. Now I will see if it works when I try to build the chart.

**Comment by Pierre-Sassoulas** [comment]
I added tests for MacOs and Windows on Travis, and all the test pass with 99% coverage using `from pysankey import sankey`. See here:  https://travis-ci.org/Pierre-Sassoulas/pySankey/builds/641838414.  I did not change anything in the package though, so I still don't understand what is wrong with your setup. I suspect pySankey is installed and not pySankeyBeta. Still investigating.
